### ISSUE TITLE
Crashes on Android when scrolling immediately after window opening due to ActivityIndicator.

### ISSUE THREAD

**Issue by davide-ensini** [Topener/nl.fokkezb.infiniteScroll#35]
Hi, I had some problems with this bug that is most likely not due to your code. 
It happens only when i scroll down immediately after i see the window.
It disappears when I comment out the lines that add and remove ActivityIndcator from the View it belongs to.
I thought you might be interested in knowing this. Thanks for your work.

**Comment by FokkeZB** [comment]
Thanks, if you find a workaround for this, please let me know. I'll keep the issue open for others to see.

**Comment by Topener** [comment]
@davide-ensini have you managed to find a solution/workaround for this?

**Comment by davide-ensini** [comment]
@Topener actually not, I decided to wait to find a working solution for this until I really needed infinite scroll. It turned out I didn't need it, sorry

**Comment by Topener** [comment]
Then I'll close the issue for now ;)
