### ISSUE TITLE
How to combine this module with module ticollectionview

### ISSUE THREAD

**Issue by dekoci** [Topener/nl.fokkezb.infiniteScroll#44]
like in the changelog 1.4.4 is now support with ticollectionview.

But I tried to add module and method as an example

``` javascript
<Collection src="myPhotos" id="listPhotos" instance="true" />
<Window>
<ListView id="listView" backgroundColor="white" defaultItemTemplate="template" module="de.marcelpociot.collectionview" method="createCollectionView">
    <Templates>
        <ItemTemplate name="template">
            <View id="photo_page">
                <View id="photoWrap" onClick="openPhotoDetail">
                    <ImageView class="photoImage" touchEnabled="false" bindId="thumb"/>
                    <ImageView class="photoImage" touchEnabled="false" backgroundImage="/gradient_white_black.png"/>
                    <Label id="photoRestName" touchEnabled="false" bindId="name"></Label>
                </View>
            </View>
        </ItemTemplate>
    </Templates>
    <Widget id="listWidget" src="nl.fokkezb.infiniteScroll" onEnd="listLoader"/>
    <ListSection dataCollection="$.listPhotos" module="de.marcelpociot.collectionview" method="createCollectionSection">
        <ListItem thumb:image="{thumb}" name:text="{name}"/>
    </ListSection>
</ListView>
</Window>
```

Did not return any results. Is there something wrong ?
Thaks

**Comment by FokkeZB** [comment]
Did you follow https://github.com/FokkeZB/nl.fokkezb.infiniteScroll/blob/master/README.md#use-it and call `$.listWidget.init($.listView)` in your controller?

**Comment by dekoci** [comment]
Yes, I did.
When I compile using 2 module, the log doesn't go into function listLoader();
```Javascript
function listLoader(e)
{
	console.log('foo');
  	myLoader(e, $.listPhotos);
}
```
But if I removed the ticollection module, infinite scroll works fine.

**Comment by FokkeZB** [comment]
I'm afraid I don't have time to dive into this atm. I'd suggest to check out the compiled code in the `Resources` folder to see if you can find out why it isn't working. Maybe add some log calls in the widget.

**Comment by skypanther** [comment]
FYI, I've found the same issue when combining with your pull-to-refresh widget. The onEnd() callback is never firing.

**Comment by FokkeZB** [comment]
@skypanther could you debug this together with @dekoci? Or at least get me a zip of a project and steps that 100% reproduce? I only have very little time in the evenings for this, sorry.
