### ISSUE TITLE
Nice to have: onStart

### ISSUE THREAD

**Issue by Arialle** [Topener/nl.fokkezb.infiniteScroll#50]
I was looking into this module to create a chatting program. As the module is right now, there doesn't seem to have any way to infinitely scroll upwards to add more data.

**Comment by FokkeZB** [comment]
Mmm, interesting use case. I guess the main changes would be in `mark()` and `onScroll()`. I can't look into it now, but am open to PRs!

**Comment by nuno** [comment]
+ 1 "infinitely scroll upwards to add more data"

**Comment by Topener** [comment]
Currently there is no real support for infinite scroll upwards on TableViews/ListViews in Titanium. The `mark` event doesn't work either when going upwards. For this to be added to this module we'd first need a proper `mark` event the other way unless someone has a better idea.

Did you manage to implement it differently @Arialle?
