### ISSUE TITLE
Using with search option

### ISSUE THREAD

**Issue by avines002** [Topener/nl.fokkezb.infiniteScroll#58]
I understand that using this widget with a search functionality will only show results of the items that are currently showing. I'm trying to work out a good solution for what can be done for when the user search's the list, finds no results to show, but in reality there are results, just not in what is currently showing. Is there a working solution someone has already done, or a suggested way to handle this?

**Comment by FokkeZB** [comment]
Wow, I don't quite follow?!

All this widget does is simply give you an event when the user has reached the end of the list. Everything else is up to you.
