### ISSUE TITLE
How to combine this widget with Pull to Refresh Widget 

### ISSUE THREAD

**Issue by ibudhiraja** [Topener/nl.fokkezb.infiniteScroll#59]
Hi Fokke,

I have tried to integrate both of your widgets in single ListView and also in table view. but not able to integrate successfully. After using both widgets either app got crashed or data on list view is not visible. Can you please help me in this scenario or give the example code. 

Thanks

**Comment by FokkeZB** [comment]
Do you have any information on the crash specifics as well as an example of how you integrated the widgets?
